[project]
name = "lib-reader"
version = "0.1.0"
description = "Reader for GRID payloads (03B/04/05B/07/09/10B/11B/12B and GRIDN1)"
authors = [
    { name = "wqd", email = "wqd.2019@tsinghua.org.cn" }
]
dependencies = [
    "numpy>=1.24.4",
    "addict>=2.4.0",
    "polars>=0.20.0",
    "numba>=0.58.1",
    "lmfit>=1.2.2",
    "scipy>=1.10.1",
    "crcmod>=1.7",
    "matplotlib>=3.7.2",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true
