tb:
  default_bkg: lin
  background_overrides: {}
  peak_overrides: {}
  qa: {}
ec_source:
  default_bkg: lin
  background_overrides: {}
  peak_overrides: {}
  qa: {}
ec_xray:
  default_bkg: lin
  background_overrides: {}
  peak_overrides: {}
  qa: {}
