version: GRIDN1/GAGG
tb:
  reader: n1
  bin_width: 4
  adc_max: 16384.0
  science_dir: raw_data
  fit_range_file: fit_range_tb.yaml
  channels:
  - 1
  - 2
  tb_fit_maxfev: 100000
  skip_qa_fail: true
  tb_fit_p0_by_channel:
    '1':
    - 0.0003296
    - 0.0182
    - 23.87
    - 64.7
    - 51970.0
    '2':
    - 0.0003775
    - 0.0188
    - 23.98
    - 66.6
    - 44760.0
ec:
  reader: n1
  bin_width: 4
  adc_max: 16384.0
  x_path: raw_data
  src_path: raw_data
  tb_ref_path: single_process/merged_tb.json
  fit_range_file: fit_range_ec_xray.yaml
  energy_map: {}
  channel_count: 4
