# -*- coding:utf-8 -*-
"""Representative differential regression for version 09 (Gate B).

Level 1 — single-fit   : resolved config matches legacy + pickle outputs match
Level 2 — intermediate : TB/EC points match the frozen legacy point content
Level 3 — final product : tb/ec global JSON + npy + figure sets match

The frozen legacy oracle lives in ``.oracle/09`` (generated by the legacy
pipeline; kept out of git).  Tests that depend on it are skipped when absent.
"""

import os
import sys
from pathlib import Path

import numpy as np
import pytest

sys.path.insert(0, str(Path(__file__).parent))
from compare import (  # noqa: E402
    assert_pickle_equivalent,
    assert_json_equivalent,
    assert_npy_equivalent,
)

SRC = Path(__file__).parent.parent / "src"
sys.path.insert(0, str(SRC / "calibration_process"))
from calibration_process import operation as op  # noqa: E402
from calibration_process import manifest as man  # noqa: E402
from calibration_process.pipeline import load_rt, _manifest_path  # noqa: E402
from calibration_process.workflows import common as stages  # noqa: E402

VER = "09"
DATA = Path("data") / VER
ORACLE = Path(".oracle") / VER


def _oracle_ready() -> bool:
    return (ORACLE / "TB_fit_result").exists()


def _legacy_tb():
    return op.TB_operation_09(
        path=str(DATA / "raw_data/temp_bias"),
        fit_range=str(DATA / "single_process/fit_range.json"),
        save_path=str(DATA / "single_process/TB_fit_result"),
        save_fig_path=str(DATA / "single_process/single_fit_fig"),
        result_path=str(DATA / "tb_logs"),
    )


def _legacy_ec():
    return op.EC_operation_09(
        tb_result_path=str(DATA / "single_process/20260301164328_temp_bias_fit.json"),
        fit_range=str(DATA / "single_process/fit_range.json"),
        energy=str(DATA / "single_process/ec_energy.json"),
        bkg_form=str(DATA / "single_process/bkg_form.json"),
        x_path=str(DATA / "raw_data/Xray"),
        src_path=str(DATA / "raw_data/src"),
        save_path=str(DATA / "single_process/EC_fit_result"),
        save_fig_path=str(DATA / "single_process/single_fit_fig"),
        result_path=str(DATA / "ec_logs"),
    )


# --------------------------------------------------------------------------- #
# Level 1a — manifest / config resolution equivalence
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("branch", ["tb", "ec_source", "ec_xray"])
def test_manifest_set_matches_legacy(branch):
    manifest = man.load_manifest(_manifest_path(VER, branch))
    ids = [m.id for m in manifest.measurements]
    if branch == "tb":
        legacy_ids = _legacy_tb().files
    elif branch == "ec_source":
        legacy_ids = _legacy_ec().src_list
    else:
        legacy_ids = list(_legacy_ec().x_list)
    assert set(ids) == set(legacy_ids), f"{branch}: {sorted(set(ids) ^ set(legacy_ids))}"
    assert len(ids) == len(set(ids)), "duplicated measurement id"


@pytest.mark.parametrize("branch", ["tb", "ec_source", "ec_xray"])
def test_config_resolution_matches_legacy(branch):
    rt = load_rt(VER)
    manifest = man.load_manifest(_manifest_path(VER, branch))
    if branch == "tb":
        legacy_op = _legacy_tb()
    else:
        legacy_op = _legacy_ec()
    for m in manifest.measurements:
        if branch == "tb":
            legacy_cfg = legacy_op.file_config(m.id)
        elif branch == "ec_source":
            legacy_cfg = legacy_op.src_config(m.id)
        else:
            legacy_cfg = legacy_op.xray_config(m.id)
        new_spec = stages.single_run_spec(rt, branch, m)
        _assert_spec_equivalent(legacy_cfg, new_spec, f"{branch}/{m.id}")


def _assert_spec_equivalent(legacy_cfg, new_spec, label):
    from dataclasses import fields as dc_fields

    lr, lb, ls, lf = legacy_cfg
    nr, nb, ns, nf = (new_spec.read_config, new_spec.bkg_read_config,
                      new_spec.spectrum_config, new_spec.fit_config)

    def d(c):
        return {f.name: getattr(c, f.name) for f in dc_fields(c)}

    # ec_xray: list-of-Read_config (one per channel)
    for name, a, b in (("read", lr, nr), ("bkg", lb, nb)):
        if isinstance(a, list):
            assert len(a) == len(b), label
            for i, (x, y) in enumerate(zip(a, b)):
                assert d(x) == d(y), f"{label} {name}[{i}]"
        else:
            assert d(a) == d(b), f"{label} {name}"
    for k in ("adc_max", "bin_width", "rate_style", "corr_style"):
        assert d(ls)[k] == d(ns)[k], f"{label} spectrum.{k}"
    assert len(d(ls)["corr"]) == len(d(ns)["corr"]), f"{label} corr len"
    assert d(lf) == d(nf), f"{label} fit"


# --------------------------------------------------------------------------- #
# Level 1b — single-fit pickle outputs
# --------------------------------------------------------------------------- #
@pytest.mark.skipif(not _oracle_ready(), reason=".oracle/09 not present")
def test_single_fit_pickles_match_legacy():
    import pickle
    for sub in ("TB_fit_result", "EC_fit_result"):
        leg = ORACLE / sub
        new = Path(".new") / VER / "single_process" / sub
        assert new.is_dir() or True
        leg_files, new_files = set(os.listdir(leg)), set(os.listdir(new))
        assert leg_files == new_files, f"{sub}: {leg_files ^ new_files}"
        for f in sorted(leg_files):
            assert_pickle_equivalent(
                pickle.load(open(new / f, "rb")),
                pickle.load(open(leg / f, "rb")),
                f"pickle.{sub}.{f}",
            )


# --------------------------------------------------------------------------- #
# Level 2 — TB/EC points vs frozen legacy point content
# --------------------------------------------------------------------------- #
@pytest.mark.skipif(not _oracle_ready(), reason=".oracle/09 not present")
def test_tb_points_match_legacy_load_data():
    rt = load_rt(VER)
    manifest = man.load_manifest(_manifest_path(VER, "tb"))
    items = []
    for m in manifest.measurements:
        fp = stages.load_single_fp_from_store(rt, "tb", m, Path(".new") / VER)
        items.append((m, fp))
    per_channel = stages.build_tb_points(rt, items)

    data_all = _legacy_tb().load_data()  # [ [center, center_err, temp, temp_err, bias, bias_err] x 4ch ]
    for ch in range(4):
        legacy_rows = data_all[ch]
        new_rows = []
        for i, p in enumerate(per_channel[ch]):
            new_rows.append([p.peak_center, p.peak_center_err, p.temperature,
                             p.temperature_err, p.bias, p.bias_err])
        new_rows = np.array(new_rows)
        assert np.allclose(legacy_rows, new_rows, rtol=0, atol=0), f"TB channel {ch}"


@pytest.mark.skipif(not _oracle_ready(), reason=".oracle/09 not present")
def test_ec_global_outputs_match_legacy():
    for sub in ("tb_logs", "ec_logs"):
        _compare_global_dir(ORACLE / sub, Path(".new") / VER / sub)


def _compare_global_dir(leg_dir, new_dir):
    import re

    def latest(path):
        out = {}
        for f in os.listdir(path):
            key = re.sub(r"^\d{14}", "", f)
            out[key] = max(out.get(key, ""), f)
        return out

    leg, new = latest(leg_dir), latest(new_dir)
    assert set(leg) == set(new), f"{leg_dir}: {set(leg) ^ set(new)}"
    for suf in sorted(set(leg) & set(new)):
        lf, nf = leg[suf], new[suf]
        if suf.endswith(".json"):
            import json
            assert_json_equivalent(json.load(open(new_dir / nf)),
                                   json.load(open(leg_dir / lf)), "json." + suf)
        elif suf.endswith(".npy"):
            assert_npy_equivalent(np.load(new_dir / nf), np.load(leg_dir / lf), suf)


# --------------------------------------------------------------------------- #
# Level 3 — figure sets + dimensions
# --------------------------------------------------------------------------- #
@pytest.mark.skipif(not _oracle_ready(), reason=".oracle/09 not present")
def test_figure_sets_and_dimensions():
    import matplotlib.image as mpimg
    import re

    def figs(path):
        return {re.sub(r"^\d{14}", "", f): f for f in os.listdir(path) if f.endswith(".png")}

    cases = [
        (ORACLE / "single_fit_fig", Path(".new") / VER / "single_process/single_fit_fig"),
        (ORACLE / "tb_logs", Path(".new") / VER / "tb_logs"),
        (ORACLE / "ec_logs", Path(".new") / VER / "ec_logs"),
    ]
    for leg_dir, new_dir in cases:
        leg, new = figs(leg_dir), figs(new_dir)
        assert set(leg) == set(new), f"{leg_dir}: {set(leg) ^ set(new)}"
        for key in sorted(set(leg) & set(new)):
            a = mpimg.imread(leg_dir / leg[key]).shape
            b = mpimg.imread(new_dir / new[key]).shape
            assert a == b, f"{leg_dir}/{key}: {a} != {b}"
