version: 14B
branch: tb
measurements:
- id: 0C-265-131
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/0C-265-131.event.dat
  hk_files:
  - raw_data/Temp_Vbias/0C-265-ecu_220.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 0C-270-133
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/0C-270-133.event.dat
  hk_files:
  - raw_data/Temp_Vbias/0C-270-ecu_222.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 0C-275-134
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/0C-275-134.event.dat
  hk_files:
  - raw_data/Temp_Vbias/0C-275-ecu_223.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 0C-280-135
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/0C-280-135.event.dat
  hk_files:
  - raw_data/Temp_Vbias/0C-280-ecu_224.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 0C-283-136
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/0C-283-136.event.dat
  hk_files:
  - raw_data/Temp_Vbias/0C-283-ecu_225.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 0C-285-137
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/0C-285-137.event.dat
  hk_files:
  - raw_data/Temp_Vbias/0C-285-ecu_226.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 0C-287-138
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/0C-287-138.event.dat
  hk_files:
  - raw_data/Temp_Vbias/0C-287-ecu_227.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 0C-290-139
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/0C-290-139.event.dat
  hk_files:
  - raw_data/Temp_Vbias/0C-290-ecu_228.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 10C-265-140
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/10C-265-140.event.dat
  hk_files:
  - raw_data/Temp_Vbias/10C-265-ecu_230.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 10C-270-141
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/10C-270-141.event.dat
  hk_files:
  - raw_data/Temp_Vbias/10C-270-ecu_231.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 10C-275-142
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/10C-275-142.event.dat
  hk_files:
  - raw_data/Temp_Vbias/10C-275-ecu_232.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 10C-280-143
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/10C-280-143.event.dat
  hk_files:
  - raw_data/Temp_Vbias/10C-280-ecu_233.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 10C-283-144
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/10C-283-144.event.dat
  hk_files:
  - raw_data/Temp_Vbias/10C-283-ecu_234.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 10C-285-145
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/10C-285-145.event.dat
  hk_files:
  - raw_data/Temp_Vbias/10C-285-ecu_235.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 10C-287-147
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/10C-287-147.event.dat
  hk_files:
  - raw_data/Temp_Vbias/10C-287-ecu_237.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 10C-290-148
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/10C-290-148.event.dat
  hk_files:
  - raw_data/Temp_Vbias/10C-290-ecu_238.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 20C-265-150
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/20C-265-150.event.dat
  hk_files:
  - raw_data/Temp_Vbias/20C-265-ecu_241.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 20C-270-153
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/20C-270-153.event.dat
  hk_files:
  - raw_data/Temp_Vbias/20C-270-ecu_244.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 20C-275-154
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/20C-275-154.event.dat
  hk_files:
  - raw_data/Temp_Vbias/20C-275-ecu_245.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 20C-280-155
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/20C-280-155.event.dat
  hk_files:
  - raw_data/Temp_Vbias/20C-280-ecu_246.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 20C-283-156
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/20C-283-156.event.dat
  hk_files:
  - raw_data/Temp_Vbias/20C-283-ecu_247.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 20C-285-158
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/20C-285-158.event.dat
  hk_files:
  - raw_data/Temp_Vbias/20C-285-ecu_249.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 20C-287-159
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/20C-287-159.event.dat
  hk_files:
  - raw_data/Temp_Vbias/20C-287-ecu_250.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 20C-290-160
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/20C-290-160.event.dat
  hk_files:
  - raw_data/Temp_Vbias/20C-290-ecu_251.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 30C-265-165
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/30C-265-165.event.dat
  hk_files:
  - raw_data/Temp_Vbias/30C-265-ecu_004.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 30C-270-168
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/30C-270-168.event.dat
  hk_files:
  - raw_data/Temp_Vbias/30C-270-ecu_007.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 30C-275-169
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/30C-275-169.event.dat
  hk_files:
  - raw_data/Temp_Vbias/30C-275-ecu_008.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 30C-280-170
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/30C-280-170.event.dat
  hk_files:
  - raw_data/Temp_Vbias/30C-280-ecu_009.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 30C-283-172
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/30C-283-172.event.dat
  hk_files:
  - raw_data/Temp_Vbias/30C-283-ecu_011.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 30C-285-173
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/30C-285-173.event.dat
  hk_files:
  - raw_data/Temp_Vbias/30C-285-ecu_012.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 30C-287-174
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/30C-287-174.event.dat
  hk_files:
  - raw_data/Temp_Vbias/30C-287-ecu_013.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: 30C-290-175
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/30C-290-175.event.dat
  hk_files:
  - raw_data/Temp_Vbias/30C-290-ecu_014.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m10C-265-129
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m10C-265-129.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m10C-265-ecu_218.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m10C-270-120
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m10C-270-120.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m10C-270-ecu_209.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m10C-275-121
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m10C-275-121.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m10C-275-ecu_210.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m10C-280-122
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m10C-280-122.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m10C-280-ecu_211.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m10C-283-125
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m10C-283-125.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m10C-283-ecu_214.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m10C-285-126
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m10C-285-126.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m10C-285-ecu_215.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m10C-287-127
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m10C-287-127.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m10C-287-ecu_216.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m10C-290-128
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m10C-290-128.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m10C-290-ecu_217.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m20C-265-101
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m20C-265-101.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m20C-265-ecu_186.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m20C-270-102
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m20C-270-102.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m20C-270-ecu_187.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m20C-275-103
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m20C-275-103.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m20C-275-ecu_188.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m20C-280-104
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m20C-280-104.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m20C-280-ecu_189.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m20C-283-105
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m20C-283-105.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m20C-283-ecu_190.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m20C-285-100
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m20C-285-100.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m20C-285-ecu_184.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m20C-287-106
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m20C-287-106.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m20C-287-ecu_191.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m20C-290-107
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m20C-290-107.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m20C-290-ecu_192.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m30C-265-109
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m30C-265-109.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m30C-265-ecu_194.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m30C-270-112
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m30C-270-112.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m30C-270-ecu_199.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m30C-275-113
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m30C-275-113.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m30C-275-ecu_200.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m30C-280-114
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m30C-280-114.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m30C-280-ecu_201.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m30C-283-115
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m30C-283-115.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m30C-283-ecu_202.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m30C-285-116
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m30C-285-116.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m30C-285-ecu_203.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m30C-287-117
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m30C-287-117.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m30C-287-ecu_204.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: m30C-290-118
  branch: tb
  science_files:
  - raw_data/Temp_Vbias/m30C-290-118.event.dat
  hk_files:
  - raw_data/Temp_Vbias/m30C-290-ecu_206.hk
  aux_files: []
  metadata: {}
  use: true
  channels: null
