version: 15B
branch: tb
measurements:
- id: 0C_265
  branch: tb
  science_files:
  - raw_data/0C_265_039.event.dat
  hk_files:
  - raw_data/0C_265_ecu_077.hk
  aux_files: []
  metadata:
    hk_bias: 26.5
  use: true
  channels: null
- id: 0C_270
  branch: tb
  science_files:
  - raw_data/0C_270_040.event.dat
  hk_files:
  - raw_data/0C_270_ecu_078.hk
  aux_files: []
  metadata:
    hk_bias: 27.0
  use: true
  channels: null
- id: 0C_275
  branch: tb
  science_files:
  - raw_data/0C_275_041.event.dat
  hk_files:
  - raw_data/0C_275_ecu_079.hk
  aux_files: []
  metadata:
    hk_bias: 27.5
  use: true
  channels: null
- id: 0C_280
  branch: tb
  science_files:
  - raw_data/0C_280_042.event.dat
  hk_files:
  - raw_data/0C_280_ecu_080.hk
  aux_files: []
  metadata:
    hk_bias: 28.0
  use: true
  channels: null
- id: 0C_283
  branch: tb
  science_files:
  - raw_data/0C_283_043.event.dat
  hk_files:
  - raw_data/0C_283_ecu_081.hk
  aux_files: []
  metadata:
    hk_bias: 28.3
  use: true
  channels: null
- id: 0C_285
  branch: tb
  science_files:
  - raw_data/0C_285_044.event.dat
  hk_files:
  - raw_data/0C_285_ecu_083.hk
  aux_files: []
  metadata:
    hk_bias: 28.5
  use: true
  channels: null
- id: 0C_287
  branch: tb
  science_files:
  - raw_data/0C_287_045.event.dat
  hk_files:
  - raw_data/0C_287_ecu_084.hk
  aux_files: []
  metadata:
    hk_bias: 28.7
  use: true
  channels: null
- id: 0C_290
  branch: tb
  science_files:
  - raw_data/0C_290_046.event.dat
  hk_files:
  - raw_data/0C_290_ecu_085.hk
  aux_files: []
  metadata:
    hk_bias: 29.0
  use: true
  channels: null
- id: 10C_265
  branch: tb
  science_files:
  - raw_data/10_265_048.event.dat
  hk_files:
  - raw_data/10_265_ecu_087.hk
  aux_files: []
  metadata:
    hk_bias: 26.5
  use: true
  channels: null
- id: 10C_270
  branch: tb
  science_files:
  - raw_data/10_270_049.event.dat
  hk_files:
  - raw_data/10_270_ecu_088.hk
  aux_files: []
  metadata:
    hk_bias: 27.0
  use: true
  channels: null
- id: 10C_275
  branch: tb
  science_files:
  - raw_data/10_275_050.event.dat
  hk_files:
  - raw_data/10_275_ecu_089.hk
  aux_files: []
  metadata:
    hk_bias: 27.5
  use: true
  channels: null
- id: 10C_280
  branch: tb
  science_files:
  - raw_data/10_280_051.event.dat
  hk_files:
  - raw_data/10_280_ecu_090.hk
  aux_files: []
  metadata:
    hk_bias: 28.0
  use: true
  channels: null
- id: 10C_283
  branch: tb
  science_files:
  - raw_data/10_283_052.event.dat
  hk_files:
  - raw_data/10_283_ecu_091.hk
  aux_files: []
  metadata:
    hk_bias: 28.3
  use: true
  channels: null
- id: 10C_285
  branch: tb
  science_files:
  - raw_data/10_285_053.event.dat
  hk_files:
  - raw_data/10_285_ecu_092.hk
  aux_files: []
  metadata:
    hk_bias: 28.5
  use: true
  channels: null
- id: 10C_287
  branch: tb
  science_files:
  - raw_data/10_287_054.event.dat
  hk_files:
  - raw_data/10_287_ecu_093.hk
  aux_files: []
  metadata:
    hk_bias: 28.7
  use: true
  channels: null
- id: 10C_290
  branch: tb
  science_files:
  - raw_data/10_290_055.event.dat
  hk_files:
  - raw_data/10_290_ecu_094.hk
  aux_files: []
  metadata:
    hk_bias: 29.0
  use: true
  channels: null
- id: 20C_265
  branch: tb
  science_files:
  - raw_data/20_265_060.event.dat
  hk_files:
  - raw_data/20_265_ecu_099.hk
  aux_files: []
  metadata:
    hk_bias: 26.5
  use: true
  channels: null
- id: 20C_270
  branch: tb
  science_files:
  - raw_data/20_270_058.event.dat
  hk_files:
  - raw_data/20_270_ecu_097.hk
  aux_files: []
  metadata:
    hk_bias: 27.0
  use: true
  channels: null
- id: 20C_275
  branch: tb
  science_files:
  - raw_data/20_275_061.event.dat
  hk_files:
  - raw_data/20_275_ecu_100.hk
  aux_files: []
  metadata:
    hk_bias: 27.5
  use: true
  channels: null
- id: 20C_280
  branch: tb
  science_files:
  - raw_data/20_280_064.event.dat
  hk_files:
  - raw_data/20_280_ecu_103.hk
  aux_files: []
  metadata:
    hk_bias: 28.0
  use: true
  channels: null
- id: 20C_283
  branch: tb
  science_files:
  - raw_data/20_283_065.event.dat
  hk_files:
  - raw_data/20_283_ecu_104.hk
  aux_files: []
  metadata:
    hk_bias: 28.3
  use: true
  channels: null
- id: 20C_285
  branch: tb
  science_files:
  - raw_data/20_285_066.event.dat
  hk_files:
  - raw_data/20_285_ecu_106.hk
  aux_files: []
  metadata:
    hk_bias: 28.5
  use: true
  channels: null
- id: 20C_287
  branch: tb
  science_files:
  - raw_data/20_287_067.event.dat
  hk_files:
  - raw_data/20_287_ecu_107.hk
  aux_files: []
  metadata:
    hk_bias: 28.7
  use: true
  channels: null
- id: 20C_290
  branch: tb
  science_files:
  - raw_data/20_290_068.event.dat
  hk_files:
  - raw_data/20_290_ecu_108.hk
  aux_files: []
  metadata:
    hk_bias: 29.0
  use: true
  channels: null
- id: 30C_265
  branch: tb
  science_files:
  - raw_data/30_265_070.event.dat
  hk_files:
  - raw_data/30_265_ecu_111.hk
  aux_files: []
  metadata:
    hk_bias: 26.5
    note: lowest gain / threshold-adjacent, single fit unreliable (QA fail all channels)
  use: false
  channels: null
- id: 30C_270
  branch: tb
  science_files:
  - raw_data/30_270_071.event.dat
  hk_files:
  - raw_data/30_270_ecu_112.hk
  aux_files: []
  metadata:
    hk_bias: 27.0
  use: true
  channels: null
- id: 30C_275
  branch: tb
  science_files:
  - raw_data/30_275_072.event.dat
  hk_files:
  - raw_data/30_275_ecu_113.hk
  aux_files: []
  metadata:
    hk_bias: 27.5
  use: true
  channels: null
- id: 30C_280
  branch: tb
  science_files:
  - raw_data/30_280_074.event.dat
  hk_files:
  - raw_data/30_280_ecu_115.hk
  aux_files: []
  metadata:
    hk_bias: 28.0
  use: true
  channels: null
- id: 30C_283
  branch: tb
  science_files:
  - raw_data/30_283_075.event.dat
  hk_files:
  - raw_data/30_283_ecu_116.hk
  aux_files: []
  metadata:
    hk_bias: 28.3
  use: true
  channels: null
- id: 30C_285
  branch: tb
  science_files:
  - raw_data/30_285_076.event.dat
  hk_files:
  - raw_data/30_285_ecu_117.hk
  aux_files: []
  metadata:
    hk_bias: 28.5
  use: true
  channels: null
- id: 30C_287
  branch: tb
  science_files:
  - raw_data/30_287_078.event.dat
  hk_files:
  - raw_data/30_287_ecu_119.hk
  aux_files: []
  metadata:
    hk_bias: 28.7
  use: true
  channels: null
- id: 30C_290
  branch: tb
  science_files:
  - raw_data/30_290_079.event.dat
  hk_files:
  - raw_data/30_290_ecu_120.hk
  aux_files: []
  metadata:
    hk_bias: 29.0
  use: true
  channels: null
- id: m10C_265
  branch: tb
  science_files:
  - raw_data/m10_265_030.event.dat
  hk_files:
  - raw_data/m10_265_ecu_068.hk
  aux_files: []
  metadata:
    hk_bias: 26.5
  use: true
  channels: null
- id: m10C_270
  branch: tb
  science_files:
  - raw_data/m10_270_031.event.dat
  hk_files:
  - raw_data/m10_270_ecu_069.hk
  aux_files: []
  metadata:
    hk_bias: 27.0
  use: true
  channels: null
- id: m10C_275
  branch: tb
  science_files:
  - raw_data/m10_275_032.event.dat
  hk_files:
  - raw_data/m10_275_ecu_070.hk
  aux_files: []
  metadata:
    hk_bias: 27.5
  use: true
  channels: null
- id: m10C_280
  branch: tb
  science_files:
  - raw_data/m10_280_033.event.dat
  hk_files:
  - raw_data/m10_280_ecu_071.hk
  aux_files: []
  metadata:
    hk_bias: 28.0
  use: true
  channels: null
- id: m10C_283
  branch: tb
  science_files:
  - raw_data/m10_283_034.event.dat
  hk_files:
  - raw_data/m10_283_ecu_072.hk
  aux_files: []
  metadata:
    hk_bias: 28.3
  use: true
  channels: null
- id: m10C_285
  branch: tb
  science_files:
  - raw_data/m10_285_035.event.dat
  hk_files:
  - raw_data/m10_285_ecu_073.hk
  aux_files: []
  metadata:
    hk_bias: 28.5
  use: true
  channels: null
- id: m10C_287
  branch: tb
  science_files:
  - raw_data/m10_287_036.event.dat
  hk_files:
  - raw_data/m10_287_ecu_074.hk
  aux_files: []
  metadata:
    hk_bias: 28.7
  use: true
  channels: null
- id: m10C_290
  branch: tb
  science_files:
  - raw_data/m10_290_037.event.dat
  hk_files:
  - raw_data/m10_290_ecu_075.hk
  aux_files: []
  metadata:
    hk_bias: 29.0
  use: true
  channels: null
- id: m20C_265
  branch: tb
  science_files:
  - raw_data/m20C-265-012.event.dat
  hk_files:
  - raw_data/m20C-265-ecu_047.hk
  aux_files: []
  metadata:
    hk_bias: 26.5
  use: true
  channels: null
- id: m20C_270
  branch: tb
  science_files:
  - raw_data/m20C-270-013.event.dat
  hk_files:
  - raw_data/m20C-270-ecu_048.hk
  aux_files: []
  metadata:
    hk_bias: 27.0
  use: true
  channels: null
- id: m20C_275
  branch: tb
  science_files:
  - raw_data/m20C-275-014.event.dat
  hk_files:
  - raw_data/m20C-275-ecu_049.hk
  aux_files: []
  metadata:
    hk_bias: 27.5
  use: true
  channels: null
- id: m20C_280
  branch: tb
  science_files:
  - raw_data/m20C-280-015.event.dat
  hk_files:
  - raw_data/m20C-280-ecu_050.hk
  aux_files: []
  metadata:
    hk_bias: 28.0
  use: true
  channels: null
- id: m20C_283
  branch: tb
  science_files:
  - raw_data/m20C-283-016.event.dat
  hk_files:
  - raw_data/m20C-283-ecu_051.hk
  aux_files: []
  metadata:
    hk_bias: 28.3
  use: true
  channels: null
- id: m20C_285
  branch: tb
  science_files:
  - raw_data/m20C-285-017.event.dat
  hk_files:
  - raw_data/m20C-285-ecu_052.hk
  aux_files: []
  metadata:
    hk_bias: 28.5
  use: true
  channels: null
- id: m20C_287
  branch: tb
  science_files:
  - raw_data/m20C-287-018.event.dat
  hk_files:
  - raw_data/m20C-287-ecu_053.hk
  aux_files: []
  metadata:
    hk_bias: 28.7
  use: true
  channels: null
- id: m20C_290
  branch: tb
  science_files:
  - raw_data/m20C-290-019.event.dat
  hk_files:
  - raw_data/m20C-290-ecu_054.hk
  aux_files: []
  metadata:
    hk_bias: 29.0
  use: true
  channels: null
- id: m30C_265
  branch: tb
  science_files:
  - raw_data/m30_265_022.event.dat
  hk_files:
  - raw_data/m30_265_ecu_059.hk
  aux_files: []
  metadata:
    hk_bias: 26.5
  use: true
  channels: null
- id: m30C_270
  branch: tb
  science_files:
  - raw_data/m30_270_023.event.dat
  hk_files:
  - raw_data/m30_270_ecu_060.hk
  aux_files: []
  metadata:
    hk_bias: 27.0
  use: true
  channels: null
- id: m30C_275
  branch: tb
  science_files:
  - raw_data/m30_275_024.event.dat
  hk_files:
  - raw_data/m30_275_ecu_061.hk
  aux_files: []
  metadata:
    hk_bias: 27.5
  use: true
  channels: null
- id: m30C_280
  branch: tb
  science_files:
  - raw_data/m30_280_025.event.dat
  hk_files:
  - raw_data/m30_280_ecu_062.hk
  aux_files: []
  metadata:
    hk_bias: 28.0
  use: true
  channels: null
- id: m30C_283
  branch: tb
  science_files:
  - raw_data/m30_283_026.event.dat
  hk_files:
  - raw_data/m30_283_ecu_063.hk
  aux_files: []
  metadata:
    hk_bias: 28.3
  use: true
  channels: null
- id: m30C_285
  branch: tb
  science_files:
  - raw_data/m30_285_027.event.dat
  hk_files:
  - raw_data/m30_285_ecu_064.hk
  aux_files: []
  metadata:
    hk_bias: 28.5
  use: true
  channels: null
- id: m30C_287
  branch: tb
  science_files:
  - raw_data/m30_287_028.event.dat
  hk_files:
  - raw_data/m30_287_ecu_065.hk
  aux_files: []
  metadata:
    hk_bias: 28.7
  use: true
  channels: null
- id: m30C_290
  branch: tb
  science_files:
  - raw_data/m30_290_029.event.dat
  hk_files:
  - raw_data/m30_290_ecu_066.hk
  aux_files: []
  metadata:
    hk_bias: 29.0
  use: true
  channels: null
