version: GRIDN1/EC
branch: ec_source
measurements:
- id: Co60C-40m-209.event.dat
  branch: ec_source
  science_files:
  - ec_src/Co60C-40m-209.event.dat
  hk_files: []
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: Co60C-70m-209.event.dat
  branch: ec_source
  science_files:
  - ec_src/Co60C-70m-209.event.dat
  hk_files: []
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: Cs137C-30m-208.event.dat
  branch: ec_source
  science_files:
  - ec_src/Cs137C-30m-208.event.dat
  hk_files: []
  aux_files: []
  metadata: {}
  use: true
  channels: null
- id: Cs137C-90m-208.event.dat
  branch: ec_source
  science_files:
  - ec_src/Cs137C-90m-208.event.dat
  hk_files: []
  aux_files: []
  metadata: {}
  use: true
  channels: null
