version: GRIDN1/EC
branch: ec_xray
measurements:
- id: '15'
  branch: ec_xray
  science_files:
  - ''
  - ec_xray_low/15-ch1-084.event.dat
  - ec_xray_low/15-ch2-084.event.dat
  - ec_xray_low/15-ch3-084.event.dat
  hk_files: []
  aux_files: []
  metadata:
    energy: 15.0
  use: true
  channels: null
- id: '20'
  branch: ec_xray
  science_files:
  - ''
  - ec_xray_low/20-ch1-084.event.dat
  - ec_xray_low/20-ch2-084.event.dat
  - ec_xray_low/20-ch3-084.event.dat
  hk_files: []
  aux_files: []
  metadata:
    energy: 20.0
  use: true
  channels: null
- id: '25'
  branch: ec_xray
  science_files:
  - ''
  - ec_xray_low/25-ch1-084.event.dat
  - ec_xray_low/25-ch2-084.event.dat
  - ec_xray_low/25-ch3-084.event.dat
  hk_files: []
  aux_files: []
  metadata:
    energy: 25.0
  use: true
  channels: null
- id: '30'
  branch: ec_xray
  science_files:
  - ''
  - ec_xray_low/30-ch1-084.event.dat
  - ec_xray_low/30-ch2-084.event.dat
  - ec_xray_low/30-ch3-084.event.dat
  hk_files: []
  aux_files: []
  metadata:
    energy: 30.0
  use: true
  channels: null
- id: '35'
  branch: ec_xray
  science_files:
  - ''
  - ec_xray_low/35-ch1-084.event.dat
  - ec_xray_low/35-ch2-084.event.dat
  - ec_xray_low/35-ch3-084.event.dat
  hk_files: []
  aux_files: []
  metadata:
    energy: 35.0
  use: true
  channels: null
- id: '40'
  branch: ec_xray
  science_files:
  - ec_xray/40-ch0-089.event.dat
  - ec_xray/40-ch1-089.event.dat
  - ec_xray/40-ch2-089.event.dat
  - ec_xray/40-ch3-089.event.dat
  hk_files: []
  aux_files: []
  metadata:
    energy: 40.0
  use: true
  channels: null
- id: '45'
  branch: ec_xray
  science_files:
  - ec_xray/45-ch0-090.event.dat
  - ec_xray/45-ch1-090.event.dat
  - ec_xray/45-ch2-090.event.dat
  - ec_xray/45-ch3-090.event.dat
  hk_files: []
  aux_files: []
  metadata:
    energy: 45.0
  use: true
  channels: null
- id: '47'
  branch: ec_xray
  science_files:
  - ec_xray/47-ch0-091.event.dat
  - ec_xray/47-ch1-091.event.dat
  - ec_xray/47-ch2-091.event.dat
  - ec_xray/47-ch3-091.event.dat
  hk_files: []
  aux_files: []
  metadata:
    energy: 47.0
  use: true
  channels: null
- id: '49'
  branch: ec_xray
  science_files:
  - ec_xray/49-ch0-092.event.dat
  - ec_xray/49-ch1-092.event.dat
  - ec_xray/49-ch2-092.event.dat
  - ec_xray/49-ch3-092.event.dat
  hk_files: []
  aux_files: []
  metadata:
    energy: 49.0
  use: true
  channels: null
- id: '51'
  branch: ec_xray
  science_files:
  - ec_xray/51-ch0-093.event.dat
  - ec_xray/51-ch1-093.event.dat
  - ec_xray/51-ch2-093.event.dat
  - ec_xray/51-ch3-093.event.dat
  hk_files: []
  aux_files: []
  metadata:
    energy: 51.0
  use: true
  channels: null
- id: '53'
  branch: ec_xray
  science_files:
  - ec_xray/53-ch0-094.event.dat
  - ec_xray/53-ch1-094.event.dat
  - ec_xray/53-ch2-094.event.dat
  - ec_xray/53-ch3-094.event.dat
  hk_files: []
  aux_files: []
  metadata:
    energy: 53.0
  use: true
  channels: null
- id: '55'
  branch: ec_xray
  science_files:
  - ec_xray/55-ch0-095.event.dat
  - ec_xray/55-ch1-095.event.dat
  - ec_xray/55-ch2-095.event.dat
  - ec_xray/55-ch3-095.event.dat
  hk_files: []
  aux_files: []
  metadata:
    energy: 55.0
  use: true
  channels: null
- id: '60'
  branch: ec_xray
  science_files:
  - ec_xray/60-ch0-096.event.dat
  - ec_xray/60-ch1-096.event.dat
  - ec_xray/60-ch2-096.event.dat
  - ec_xray/60-ch3-096.event.dat
  hk_files: []
  aux_files: []
  metadata:
    energy: 60.0
  use: true
  channels: null
- id: '65'
  branch: ec_xray
  science_files:
  - ec_xray/65-ch0-097.event.dat
  - ec_xray/65-ch1-097.event.dat
  - ec_xray/65-ch2-097.event.dat
  - ec_xray/65-ch3-097.event.dat
  hk_files: []
  aux_files: []
  metadata:
    energy: 65.0
  use: true
  channels: null
- id: '70'
  branch: ec_xray
  science_files:
  - ec_xray/70-ch0-098.event.dat
  - ec_xray/70-ch1-098.event.dat
  - ec_xray/70-ch2-098.event.dat
  - ec_xray/70-ch3-098.event.dat
  hk_files: []
  aux_files: []
  metadata:
    energy: 70.0
  use: true
  channels: null
- id: '75'
  branch: ec_xray
  science_files:
  - ec_xray/75-ch0-099.event.dat
  - ec_xray/75-ch1-099.event.dat
  - ec_xray/75-ch2-099.event.dat
  - ec_xray/75-ch3-100.event.dat
  hk_files: []
  aux_files: []
  metadata:
    energy: 75.0
  use: true
  channels: null
- id: '80'
  branch: ec_xray
  science_files:
  - ec_xray/80-ch0-101.event.dat
  - ec_xray/80-ch1-101.event.dat
  - ec_xray/80-ch2-101.event.dat
  - ec_xray/80-ch3-101.event.dat
  hk_files: []
  aux_files: []
  metadata:
    energy: 80.0
  use: true
  channels: null
- id: '90'
  branch: ec_xray
  science_files:
  - ec_xray/90-ch0-102.event.dat
  - ec_xray/90-ch1-102.event.dat
  - ec_xray/90-ch2-102.event.dat
  - ec_xray/90-ch3-102.event.dat
  hk_files: []
  aux_files: []
  metadata:
    energy: 90.0
  use: true
  channels: null
