measurements:
  '40':
  - null
  - - 100
    - 300
  - - 100
    - 285
  - null
  '45':
  - null
  - - 130
    - 340
  - - 130
    - 325
  - null
  '47':
  - null
  - - 140
    - 340
  - - 140
    - 330
  - null
  '65':
  - null
  - - 205
    - 430
  - - 220
    - 415
  - null
  '70':
  - null
  - - 230
    - 470
  - - 245
    - 440
  - null
  '75':
  - null
  - - 275
    - 490
  - - 300
    - 480
  - null
  '80':
  - null
  - - 320
    - 520
  - - 330
    - 510
  - null
  '90':
  - null
  - - 355
    - 580
  - - 330
    - 585
  - null
  '55':
  - null
  - - 210
    - 360
  - - 200
    - 350
  - null
  '60':
  - null
  - - 235
    - 390
  - - 225
    - 380
  - null
  '15':
  - null
  - null
  - null
  - null
  '20':
  - null
  - null
  - null
  - null
  '25':
  - null
  - null
  - null
  - null
  '30':
  - null
  - null
  - null
  - null
  '35':
  - null
  - null
  - null
  - null
  '49':
  - null
  - - 151
    - 357
  - - 152
    - 340
  - null
  '51':
  - null
  - - 145
    - 358
  - - 143
    - 342
  - null
  '53':
  - null
  - - 152
    - 366
  - - 149
    - 350
  - null
