tb:
  default_bkg: lin
  background_overrides: {}
  peak_overrides: {}
  qa: {}
ec_source:
  default_bkg: lin
  background_overrides:
    0611_Na22_10min_240f0032.dat: lin
    0611_Cs137_30min_240f0064.dat: lin
    0611_Co60_25min_240f0032.dat: gaus
    0611_Am241_12min_240f0032.dat: lin
  peak_overrides: {}
  qa: {}
ec_xray:
  default_bkg: null
  background_overrides:
    '70': lin
    '80': lin
    '100': lin
    '40': lin
    '45': lin
    '51': lin
    '53': lin
    '55': lin
    '60': lin
    '65': lin
    '20': lin
    '25': lin
    '30': lin
    '35': lin
  peak_overrides: {}
  qa: {}
